function [fe,out] = real_life_fig3ef(use_gpu, tck_file, Niter, lambda, alpha, gpudev, dataset)

%% Example of initialization and fitting LiFE model - adapted from the script demo_LiFE
%
%  fe = real_life(use_gpu, tck_file,subnum, Niter, lambda, alpha, gpudev)
%
%  Inputs:
%  use_gpu: 1 to use GPU and 0 to use CPU
%  tck_file: name of tract file (in .tck MRtrix format). Sample tckfile for 1 million connectome is available in /demo data/WB_1M.tck
%  dwiFile: Diffusion data for model fitting
%  dwiFileRepeat: Diffusion data for cross validation
%  t1File: File name for T1-weighted image
%  Niter: Number of iterations for the optimization algorithm
%  lambda: Value regularization parameter
%  alpha: Type of regularization (1 for L1 and 0 for L2).
%  gpudev: The gpu device to be used, usually a positive integer
%
%  Outputs:
%  fe: Contains model structure
%  out: outputs containing execution times
%
%  Dependencies: Vistasoft and Matlab Brain Anatomy (MBA) must be downladed and
%  added to path prior to running ReAl-LiFE. These can be found in the
%  links below:
%
%  Vistasoft: https://github.com/vistalab/vistasoft
%  MBA: https://github.com/francopestilli/mba
%
%  This file was created using demo_LiFE.m
%  Sawan Kumar (IISc), Varsha Sreenivasan (IISc), Devarajan Sridharan (IISc)
%  email: sawan.iitkgp@gmail.com, varshas@iisc.ac.in, sridhar@iisc.ac.in
%
%  Intialize a local matlab cluster if the parallel toolbox is available.
%  This helps speeding up computations espacially for large conenctomes.

addpath(genpath('/code/ReAl-LiFE'));
addpath(genpath('/code/vistasoft'));
addpath(genpath('/code/mba'));
rmpath('/code/ReAl-LiFE/mexfiles');

% Build the file names for the diffusion data, the anatomical MRI.


dwiFile       = sprintf('/data/Fig_3/raw_data/dataset_%s/D1/dwi_01.nii.gz',dataset);
dwiFileRepeat = sprintf('/data/Fig_3/raw_data/dataset_%s/D1/dwi_01.nii.gz',dataset);
t1File        = sprintf('/data/Fig_3/raw_data/dataset_%s/D1/t1.nii.gz');

%Tractography connectome
fgFileName = tck_file;

% The final connectome and data astructure will be saved with this name:
feFileName    = sprintf('LiFE');

%% (1.1) Initialize the LiFE model structure, 'fe' in the code below.
% This structure contains the forward model of diffusion based on the
% tractography solution. It also contains all the information necessary to
% compute model accuracry, and perform statistical tests. You can type
% help('feBuildModel') in the MatLab prompt for more information.

L = 360; % Discretization parameter
fe = feConnectomeInit(dwiFile,fgFileName,feFileName,[],dwiFileRepeat,t1File,L,[1,0]);


%% (1.2) Fit the model.
% Hereafter we fit the forward model of tracrography using a least-squared
% method. The information generated by fitting the model (fiber weights
% etc) is then installed in the LiFE structure.

M = feGet(fe,'model');

for reg = 1:length(alpha)
    
    for l = 1:length(lambda)
        if use_gpu
            
            %Set regularization parameter
            M.lambda = lambda(l);
            M.alpha = alpha(reg);
            
            %Set gpu device id
            M.gpudev = gpudev;
            method = 'bbnnls_gpu';
        else
            
            method = 'bbnnls';
        end
        
        [fit, out, ~, ~] = feFitModel(M,feGet(fe,'dsigdemeaned'),method,Niter,'preconditioner');
        fe = feSet(fe,'fit',fit);
        
        cv_rmse(l,reg) = feGetRep(fe,'total rmse'); % total cross validation error
        w_L1norm(l,reg) = sum(fe.life.fit.weights);
        w_L2norm(l,reg) = norm(fe.life.fit.weights,2);
        
    end
    
end

% Save the output

fname = sprintf('/results/Fig_3/fe_stats_ReAl_LiFE_regularizations_%s.mat',dataset);
save(fname,'cv_rmse','w_L1norm','w_L2norm','-v7.3');







